/**
 * mainnet.js — Mainnet wallet generator (Real Implementation)
 *
 * Generates a new Ethereum-compatible wallet (secp256k1) that works on
 * Filecoin (f4/0x addresses) and Base Sepolia (for Alkahest escrow).
 *
 * The generated wallet can receive:
 * - FIL on Calibration testnet (for gas)
 * - USDFC on Calibration testnet (for storage payments via filecoin-pin)
 * - Base Sepolia ETH (for Alkahest escrow transactions)
 */

'use strict';

const fs = require('fs');
const path = require('path');
const {
  generatePrivateKey,
  getAddressFromPrivateKey,
  maskPrivateKey,
} = require('./filecoinPay');

/**
 * Create a new mainnet-compatible wallet.
 * Generates a secp256k1 key pair and writes credentials to .env.wallet.
 *
 * @param {object} [options]
 * @param {boolean} [options.force=false] — overwrite existing .env.wallet
 * @param {string}  [options.projectRoot] — project root path (defaults to cwd)
 * @returns {Promise<{ address: string, privateKey: string, envPath: string }>}
 */
async function createMainnetWallet(options = {}) {
  const { force = false, projectRoot = process.cwd() } = options;

  const envWalletPath = path.join(projectRoot, '.env.wallet');

  // Check if wallet already exists
  if (fs.existsSync(envWalletPath) && !force) {
    const existing = fs.readFileSync(envWalletPath, 'utf8');
    const addressMatch = existing.match(/WALLET_ADDRESS=(.+)/);
    if (addressMatch && addressMatch[1].trim()) {
      const err = new Error(`Wallet already exists at ${envWalletPath}. Use --force to overwrite.`);
      err.code = 'WALLET_EXISTS';
      err.existingAddress = addressMatch[1].trim();
      throw err;
    }
  }

  // Generate new key pair
  const privateKey = generatePrivateKey();
  const address = await getAddressFromPrivateKey(privateKey);

  // Write .env.wallet file
  const envContent = [
    '# claw-pin wallet configuration',
    '# Generated by: claw-pin init',
    `# Created at: ${new Date().toISOString()}`,
    '#',
    '# ⚠️  NEVER commit this file to version control!',
    '# ⚠️  NEVER share your private key with anyone!',
    '',
    `WALLET_ADDRESS=${address}`,
    `PRIVATE_KEY=${privateKey}`,
    '',
    '# Network configuration (calibration = testnet, mainnet = real funds)',
    'FILECOIN_NETWORK=calibration',
    '',
    '# Base Sepolia RPC for Alkahest escrow',
    'BASE_SEPOLIA_RPC_URL=https://sepolia.base.org',
    '',
  ].join('\n');

  fs.writeFileSync(envWalletPath, envContent, 'utf8');

  // Also inject into current process.env so subsequent commands work immediately
  process.env.WALLET_ADDRESS = address;
  process.env.PRIVATE_KEY = privateKey;

  return {
    address,
    privateKey,
    envPath: envWalletPath,
  };
}

/**
 * Load wallet credentials from .env.wallet if it exists.
 *
 * @param {string} [projectRoot] — project root path
 * @returns {{ address: string, privateKey: string } | null}
 */
function loadWallet(projectRoot = process.cwd()) {
  const envWalletPath = path.join(projectRoot, '.env.wallet');

  if (!fs.existsSync(envWalletPath)) {
    return null;
  }

  const content = fs.readFileSync(envWalletPath, 'utf8');
  const addressMatch = content.match(/WALLET_ADDRESS=(.+)/);
  const keyMatch = content.match(/PRIVATE_KEY=(.+)/);

  if (!addressMatch || !keyMatch) {
    return null;
  }

  return {
    address: addressMatch[1].trim(),
    privateKey: keyMatch[1].trim(),
  };
}

module.exports = { createMainnetWallet, loadWallet, maskPrivateKey };
